# latexmkrc -- clase lafrox
# LuaLaTeX obligatorio (fontspec + TikZ overlay en la portada).
$pdf_mode = 4;                      # 4 = lualatex
$lualatex = 'lualatex --interaction=nonstopmode --shell-escape --synctex=1 %O %S';
$bibtex_use = 2;
$biber = 'biber %O %B';             # solo se usa con la opcion de clase [apa]
$clean_ext = 'synctex.gz run.xml bbl bcf loc lol nav snm vrb';
