// Verificador equivalente al Python cuando este entorno no ofrece intérprete.
// node verificar_drawio_aux.js [archivos .drawio o .xml]
const fs=require('fs'),path=require('path'),DIR=__dirname,E=.01;
const dec=s=>s.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&amp;/g,'&');
const attrs=s=>Object.fromEntries([...s.matchAll(/([\w]+)="([^"]*)"/g)].map(m=>[m[1],dec(m[2])]));
const style=s=>Object.fromEntries(s.split(';').filter(p=>p.includes('=')).map(p=>[p.slice(0,p.indexOf('=')),p.slice(p.indexOf('=')+1)]));
const box=(x,y,w,h)=>[x,y,x+w,y+h];
const union=(a,b)=>a?[Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.max(a[2],b[2]),Math.max(a[3],b[3])]:b;
const overlap=(a,b)=>Math.min(a[2],b[2])-Math.max(a[0],b[0])>E&&Math.min(a[3],b[3])-Math.max(a[1],b[1])>E;
function hit(p,q,b){return Math.abs(p[0]-q[0])<E?p[0]>=b[0]-E&&p[0]<=b[2]+E&&Math.min(p[1],q[1])<b[3]-E&&Math.max(p[1],q[1])>b[1]+E:p[1]>=b[1]-E&&p[1]<=b[3]+E&&Math.min(p[0],q[0])<b[2]-E&&Math.max(p[0],q[0])>b[0]+E}
function gap(p,q,r,s){if(Math.abs(p[0]-q[0])<E&&Math.abs(r[0]-s[0])<E&&Math.min(Math.max(p[1],q[1]),Math.max(r[1],s[1]))-Math.max(Math.min(p[1],q[1]),Math.min(r[1],s[1]))>E)return Math.abs(p[0]-r[0]);if(Math.abs(p[1]-q[1])<E&&Math.abs(r[1]-s[1])<E&&Math.min(Math.max(p[0],q[0]),Math.max(r[0],s[0]))-Math.max(Math.min(p[0],q[0]),Math.min(r[0],s[0]))>E)return Math.abs(p[1]-r[1]);return Infinity}
function interior(p,q,b){if(Math.abs(p[0]-q[0])<E)return p[0]>b[0]+E&&p[0]<b[2]-E&&Math.min(Math.max(p[1],q[1]),b[3])-Math.max(Math.min(p[1],q[1]),b[1])>E;if(Math.abs(p[1]-q[1])<E)return p[1]>b[1]+E&&p[1]<b[3]-E&&Math.min(Math.max(p[0],q[0]),b[2])-Math.max(Math.min(p[0],q[0]),b[0])>E;return false}
function rows(v,w,size){const lim=Math.max(1,Math.floor(w/(.62*size))),result=[];for(const line of v.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]*>/g,'').split('\n')){let current='';for(const word of line.split(/\s+/).filter(Boolean)){const next=(current+' '+word).trim();if(current&&next.length>lim){result.push(current);current=word}else current=next}result.push(current)}return result}
function textBox(v,w,size,x,y){const r=rows(v,w,size),tw=Math.max(0,...r.map(t=>t.length*.62*size))+8,th=r.length*1.2*size+8;return {r,tw,th,b:box(x-tw/2,y-th/2,tw,th)}}
function atPath(pts,relative){let distance=pts.slice(1).reduce((a,q,i)=>a+Math.abs(q[0]-pts[i][0])+Math.abs(q[1]-pts[i][1]),0)*(relative+1)/2;for(let i=0;i<pts.length-1;i++){const p=pts[i],q=pts[i+1],len=Math.abs(q[0]-p[0])+Math.abs(q[1]-p[1]);if(distance<=len+E){const t=len?distance/len:0;return [p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t,p,q]}distance-=len}return [...pts.at(-1),pts.at(-2),pts.at(-1)]}
function inspect(file){
 const xml=fs.readFileSync(file,'utf8');if(!xml.includes('<mxGraphModel'))throw Error('Falta mxGraphModel sin comprimir');
 const cells=new Map();for(const m of xml.matchAll(/<mxCell\b([^>]*?)(?:\/>|>([\s\S]*?)<\/mxCell>)/g)){const a=attrs(m[1]),inner=m[2]||'';cells.set(a.id,{...a,inner,s:style(a.style||''),g:attrs((inner.match(/<mxGeometry\b([^>]*)/)||[])[1]||'')})}
 const vs=[...cells.values()].filter(c=>c.vertex==='1'),es=[...cells.values()].filter(c=>c.edge==='1'),vm=new Map(vs.map(v=>[v.id,v]));
 const geo=new Map(),titles=new Map(),leaves=new Map(),leafParts=new Map(),groups=[],errors=[];let bounds=null,minFont=Infinity;
 const err=s=>errors.push(s);
 function abs(v){if(geo.has(v.id))return geo.get(v.id);let x=+v.g.x||0,y=+v.g.y||0;if(vm.has(v.parent)){const p=abs(vm.get(v.parent));x+=p[0];y+=p[1]}const b=box(x,y,+v.g.width||0,+v.g.height||0);geo.set(v.id,b);return b}
 for(const v of vs){const b=abs(v),s=v.s,group=s.container==='1'||s.shape==='mxgraph.aws4.group';bounds=union(bounds,b);if(group)groups.push(v);else {leaves.set(v.id,b);leafParts.set(v.id,[b])}if(!(v.value||'').trim()){if(s.shape==='mxgraph.aws4.resourceIcon')err(v.id+': icono sin rótulo');continue}const z=+s.fontSize||0;minFont=Math.min(minFont,z);if(z<24)err(v.id+': fontSize < 24');if(s.fontStyle!=='1')err(v.id+': texto sin negrita');
  if(group){const left=+s.spacingLeft||0,top=+s.spacingTop||0,avail=b[2]-b[0]-left-16,t=textBox(v.value,avail,z,0,0);if(t.r.length>1)err(v.id+': título de contenedor partido');if(t.tw>avail+E||t.th>b[3]-b[1]-top+E)err(v.id+': título desborda contenedor');const tb=box(b[0]+left,b[1]+top,t.tw,t.th);titles.set(v.id,tb);bounds=union(bounds,tb)}
  else if(s.verticalLabelPosition==='bottom'){const t=textBox(v.value,b[2]-b[0],z,(b[0]+b[2])/2,0),lb=box((b[0]+b[2]-t.tw)/2,b[3]+3,t.tw,t.th);leaves.set(v.id,union(b,lb));leafParts.set(v.id,[b,lb]);bounds=union(bounds,lb)}
  else{const space=+s.spacing||0,avail=b[2]-b[0]-2*space,t=textBox(v.value,avail,z,(b[0]+b[2])/2,(b[1]+b[3])/2);if(t.tw>avail+E||t.th>b[3]-b[1]-2*space+E)err(v.id+': texto desborda caja');leaves.set(v.id,union(b,t.b));bounds=union(bounds,t.b)}
 }
 for(const [id,a] of leaves)for(const [other,b] of leaves)if(id<other&&overlap(a,b))err(id+'/'+other+': hojas superpuestas');
 for(const [id,a] of leaves)for(const [other,b] of titles)if(overlap(a,b))err(id+': hoja sobre título '+other);
 for(const [id,parts] of leafParts)for(const b of parts)for(const g of groups){const c=geo.get(g.id),inside=b[0]>=c[0]-E&&b[1]>=c[1]-E&&b[2]<=c[2]+E&&b[3]<=c[3]+E;if(!inside&&overlap(b,c))err(id+': hoja sobre borde de '+g.id);if(inside&&(Math.abs(b[0]-c[0])<E||Math.abs(b[1]-c[1])<E||Math.abs(b[2]-c[2])<E||Math.abs(b[3]-c[3])<E))err(id+': hoja toca borde de '+g.id)}
 const paths=new Map(),edgeLabels=new Map();
 for(const e of es){const s=e.s,a=geo.get(e.source),b=geo.get(e.target);if(!a||!b){err(e.id+': extremo ausente');continue}if(['exitX','exitY','exitDx','exitDy','entryX','entryY','entryDx','entryDy'].some(k=>!(k in s)))err(e.id+': anclajes incompletos');if(s.edgeStyle!=='none'||s.rounded!=='0')err(e.id+': estilo de arista no determinista');
  const allowed=new Set();for(const endpoint of [e.source,e.target]){let id=endpoint;while(vm.has(id)){allowed.add(id);id=vm.get(id).parent}}
  const start=[a[0]+(a[2]-a[0])*(+s.exitX),a[1]+(a[3]-a[1])*(+s.exitY)],end=[b[0]+(b[2]-b[0])*(+s.entryX),b[1]+(b[3]-b[1])*(+s.entryY)];
  const points=[start,...[...e.inner.matchAll(/<mxPoint\b([^>]*)\/>/g)].filter(m=>!m[1].includes('as="offset"')).map(m=>{const a=attrs(m[1]);return [+a.x,+a.y]}),end];paths.set(e.id,points);for(const p of points)bounds=union(bounds,[p[0],p[1],p[0],p[1]]);
  for(let i=0;i<points.length-1;i++){const p=points[i],q=points[i+1];if(Math.abs(p[0]-q[0])>E&&Math.abs(p[1]-q[1])>E)err(e.id+': diagonal');for(const [id,b] of leaves)if(id!==e.source&&id!==e.target&&hit(p,q,b))err(e.id+': atraviesa hoja '+id);for(const [id,b] of titles)if(hit(p,q,b))err(e.id+': atraviesa título '+id);for(const g of groups){const c=geo.get(g.id),sides=[[[c[0],c[1]],[c[2],c[1]]],[[c[0],c[3]],[c[2],c[3]]],[[c[0],c[1]],[c[0],c[3]]],[[c[2],c[1]],[c[2],c[3]]]];if(!allowed.has(g.id)&&interior(p,q,c))err(e.id+': entra en contenedor ajeno '+g.id);for(const [r,t] of sides)if(gap(p,q,r,t)<15-E)err(e.id+': paralelo al borde de '+g.id)}const pw=+(xml.match(/pageWidth="([^"]+)"/)||[])[1]||1700,ph=+(xml.match(/pageHeight="([^"]+)"/)||[])[1]||1100;for(const [r,t] of [[[0,0],[pw,0]],[[0,ph],[pw,ph]],[[0,0],[0,ph]],[[pw,0],[pw,ph]]])if(gap(p,q,r,t)<E)err(e.id+': recorre borde del lienzo')}
  if((e.value||'').trim()){const z=+s.fontSize||0;minFont=Math.min(minFont,z);if(z<24)err(e.id+': fontSize rótulo < 24');if(s.fontStyle!=='1')err(e.id+': rótulo sin negrita');const [x,y,p,q]=atPath(points,+e.g.x||0),offMatch=e.inner.match(/<mxPoint\b([^>]*as="offset"[^>]*)\/>/),off=offMatch?attrs(offMatch[1]):{};const normal=+e.g.y||0,nx=p[1]===q[1]?0:normal,ny=p[0]===q[0]?0:normal,t=textBox(e.value,10000,z,x+nx+(+off.x||0),y+ny+(+off.y||0));edgeLabels.set(e.id,t.b);bounds=union(bounds,t.b);for(const [id,b] of leaves)if(overlap(t.b,b))err(e.id+': rótulo sobre hoja '+id);for(const [id,b] of titles)if(overlap(t.b,b))err(e.id+': rótulo sobre título '+id);for(const g of groups){const c=geo.get(g.id),r=t.b,sides=[[[c[0],c[1]],[c[2],c[1]]],[[c[0],c[3]],[c[2],c[3]]],[[c[0],c[1]],[c[0],c[3]]],[[c[2],c[1]],[c[2],c[3]]]];for(const [u,v] of sides)if(hit(u,v,r))err(e.id+': rótulo sobre borde de '+g.id)}}
 }
 for(const [id,a] of paths)for(const [other,b] of paths)if(id<other){for(let i=0;i<a.length-1;i++)for(let j=0;j<b.length-1;j++)if(gap(a[i],a[i+1],b[j],b[j+1])<15-E)err(id+'/'+other+': aristas paralelas < 15 px');for(let i=0;i<a.length-1;i++)if(edgeLabels.has(other)&&hit(a[i],a[i+1],edgeLabels.get(other)))err(id+': cruza rótulo '+other);for(let j=0;j<b.length-1;j++)if(edgeLabels.has(id)&&hit(b[j],b[j+1],edgeLabels.get(id)))err(other+': cruza rótulo '+id);if(edgeLabels.has(id)&&edgeLabels.has(other)&&overlap(edgeLabels.get(id),edgeLabels.get(other)))err(id+'/'+other+': rótulos superpuestos')}
 const width=bounds[2]-bounds[0],height=bounds[3]-bounds[1];if(width>1650+E||height>1000+E)err('extensión supera 1650 × 1000');return {width,height,minFont,errors:[...new Set(errors)]};
}
const files=process.argv.length>2?process.argv.slice(2):fs.readdirSync(DIR).filter(n=>n.endsWith('.drawio')).map(n=>path.join(DIR,n));let bad=false;if(!files.length){console.error('Sin diagramas');process.exit(1)}for(const f of files){try{const r=inspect(f);console.log(path.basename(f)+': '+r.width.toFixed(1)+' × '+r.height.toFixed(1)+' px; fuente mínima '+r.minFont+' px; '+r.errors.length+' falla(s)');for(const e of r.errors)console.log('  ERROR: '+e);bad ||=r.errors.length>0}catch(e){console.error(f+': '+e.message);bad=true}}process.exit(bad?1:0);
